---

- name: install required packages
  yum:
    name:
      - samba
      - samba-client
      - samba-winbind
      - samba-winbind-clients
      - samba-winbind-krb5-locator
      - krb5-workstation
      - pam_krb5
      - oddjob-mkhomedir
    state: installed

- name: set hostname 
  hostname:
    name: "{{ hostname }}.{{ domain }}"

- name: register ipv4 hostname
  lineinfile:
    path: /etc/hosts
    regexp: '(^127.0.0.1) (?!{{ hostname }}.{{ domain }}) (.*)'
    line: '\1 {{ hostname }}.{{ domain }} \2'
    backrefs: yes

- name: register ipv6 hostname
  lineinfile:
    path: /etc/hosts
    regexp: '(^::1) (?!{{ hostname }}.{{ domain }}) (.*)'
    line: '\1 {{ hostname }}.{{ domain }} \2'
    backrefs: yes

- name: generate samba config from template
  template:
    src: smb.conf.jinja2
    dest: /etc/samba/smb.conf
    setype: samba_etc_t
    backup: yes
  register: smbconf

- name: generate kerberos config from template
  template:
    src: krb5.conf.jinja2
    dest: /etc/krb5.conf
    setype: krb5_conf_t
    backup: yes
  register: krb5conf

- name: enable winbind auth by authconfig
  command: /usr/sbin/authconfig --enablekrb5 --enablewinbind --enablewinbindauth --enablemkhomedir --update
  when:
    - smbconf.changed
    - krb5conf.changed

- name: create home directory for domain users
  file:
    path: "/home/{{ domain | upper }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: start samba server
  systemd:
    name: smb
    state: started
    enabled: yes

- name: start nmb server
  systemd:
    name: nmb
    state: started
    enabled: yes

- name: start winbind server
  systemd:
    name: winbind
    state: started
    enabled: yes

- name: check already joined
  command: net ads testjoin -k
  register: is_joined
  ignore_errors: True
  failed_when: False
  changed_when: False

- name: join domain
  command: net ads join -U {{ domain_admin_username }}%{{ domain_admin_password}}
  when: is_joined.rc != 0

